# Generated by Django 3.1.2 on 2020-11-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
