# Generated by Django 3.1.2 on 2020-11-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20201102_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='active_duration',
        ),
        migrations.AddField(
            model_name='article',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
